### ISSUE TITLE
Indeterminism in json array comparison (LenientJsonArrayPartialMatcher), Results are differening based on array order

### ISSUE THREAD

**Issue by aymar99** [deblockt/json-diff#8]
Hello, I recently discovered your JSON comparison implementation, and it appears to be the most suitable one for my specific use case among the open-source options I explored. While playing with some examples, I encountered this scenario,

The scenario,
expected
`[
  {
    "a": 1,
    "d": 5
  },
  {
    "a": 1,
    "b": 5
  }
]`

actual
`[
  {
    "a": 1,
    "d": 2
  },
  {
    "a": 1,
    "b": 3
  }
]`

The result is,
The property "$.0.d" didn't match. Expected 5, Received: 2
The property "$.1.b" didn't match. Expected 5, Received: 3

Same scenario when order of actual is changed,

expected : same as above
actual : 
`[
  {
    "a": 1,
    "b": 3
  },
  {
    "a": 1,
    "d": 2
  }
]`

The result is 
The property "$.0.d" in the expected json is not found
The property "$.1.b" in the expected json is not found

Dependancy on order of actual for the comparison seems undesirable to me. Thoughts?

**Comment by deblockt** [comment]
Hi, 

It's a strange behavior, I will check why the order have an impact on the result.

**Comment by deblockt** [comment]
In fact this is due to comparaison issue between your object. 
When the lib compare two arrays, they compare items using a similarity rate. 
The similarity between two objects are computed base on structure (have same properties 50%) and on values (are same values 50%).
With you exemple, All object have a similarity rate of 75. 
- `{ "a": 1, "d": 5 }` and `{ "a": 1, "d": 2 }`: 2 matching property (50%), 1 matching values on two property (25%) ==> 75%
- `{ "a": 1, "d": 5 }` and `{ "a": 1, "b": 3 }`: 1 matching property (25%),  1 matching value on one property (50%) ==> 75%

I should rework the similarity rate computation to fix this issue

**Comment by deblockt** [comment]
Can you try with the 0.0.7 version?

**Comment by aymar99** [comment]
Seems to work fine, Thanks for the quick reply and fix. i am observing another issue! Have raised the same https://github.com/deblockt/json-diff/issues/12
